services:
  redis:
    image: redis:7.4.2
    container_name: redis_fastapi
    ports:
      - "6379:6379"
    networks:
      - theatre_network
    volumes:
      - redis_data:/data
    restart: always

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.3
    container_name: elasticsearch_fastapi
    restart: always
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    networks:
      - theatre_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      retries: 3
      timeout: 30s

volumes:
  es_data:
  redis_data:

networks:
  theatre_network:
    driver: bridge
